### ISSUE TITLE
The one feature i am waiting for is for Hitman Blood Money Import and Export 

### ISSUE THREAD

**Issue by benjaminwatts1971** [WSSDude/HitmanAudioTool#2]
i am pretty sure some guy named "nineearts" dId this before but for some weird reason he uploaded it on Tumblr and his project was taken down for inactivity and he is not reinstating it.
I would appreciate import and export for Blood money though it's my favourite in the series

**Comment by FDNY-7** [comment]
i also want a support for Kane & Lynch Dead Men too since it uses the same formats as Hitman Blood Money

**Comment by WSSDude** [comment]
Export should work for Hitman Blood Money at least, import needs some more research and coding still...

Exports should be almost perfect if I did not miss something obvious. Apart from other tools and scripts currently online, my exporter was validated completely that it does not mess boundaries (many exporters violited data boundaries, taking parts of other files or other errorneous behaviour like this), can export all data (apart from some hidden STR exclusives unused anywhere in game, TBD) and on top, it converts by default all of the exported audio to nicely playable PCM S16 (as internally, audio uses unconventional sample rates... verified they are indeed these odd formats already)

Plan to add more deifnitely... Need to clean up some more things, then I can try to have a look at import or Kane and Lynch etc.

Would also like to write some more proper format docs, those may be useful to some other people.

I'm closing this issue as I don't see any benefit in keeping it open.
